apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth2-proxy
  namespace: kube-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: oauth2-proxy-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: oauth2-proxy
