namespace: kube-system

resources:
  - ./externalsecret.yaml

helmCharts:
  - name: oauth2-proxy
    releaseName: oauth2-proxy
    repo: https://oauth2-proxy.github.io/manifests
    namespace: kube-system
    version: 6.23.1
    valuesInline:
      image:
        repository: "quay.io/oauth2-proxy/oauth2-proxy"
      tag: "v7.5.1"
      replicaCount: 2
      tolerations:
        - key: "arm"
          operator: "Exists"
      ingress:
        enabled: true
        className: nginx
        path: /oauth2
        pathType: Prefix
        hosts: [ auth.mlad.dk ]
      extraArgs:
        provider: oidc
        oidc-issuer-url: https://homelab-pnqnnc.zitadel.cloud
        skip-provider-button:
        pass-authorization-header:
        pass-access-token:
        pass-user-headers:
        set-authorization-header:
        email-domain: "*"
        cookie-domain: .ha.mlad
        whitelist-domain: .ha.mlad
        code-challenge-method: S256
        cookie-secure:
#      sessionStorage:
#        type: redis
      redis:
        enabled: true
        clusterDomain: homelab.mlad.dk
      config:
        existingSecret: oauth2-proxy-secret
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - oauth2-proxy
              topologyKey: "kubernetes.io/hostname"
