namespace: kube-system

resources:
  - ./externalsecret.yaml

helmCharts:
  - name: oauth2-proxy
    releaseName: oauth2-proxy
    repo: https://oauth2-proxy.github.io/manifests
    version: 6.23.1
    valuesInline:
      image:
        repository: "quay.io/oauth2-proxy/oauth2-proxy"
      tag: "v7.5.1"
      replicaCount: 2
      tolerations:
        - key: "arm"
          operator: "Exists"
      ingress:
        enabled: true
        path: /oauth2
        hosts: [ auth.mlad.dk ]
      extraArgs:
        provider: oidc
        skip-provider-button:
        pass-authorization-header:
        email-domain: "*"
        cookie-domain: .ha.mlad
        whitelist-domain: .ha.mlad
      sessionStorage:
        type: redis
      redis:
        enabled: true
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - oauth2-proxy
              topologyKey: "kubernetes.io/hostname"
      valuesFrom:
        - targetPath: config.clientID
          kind: Secret
          name: oauth2-proxy-secret
          valuesKey: ZITADEL_CLIENT_ID
        - targetPath: config.clientSecret
          kind: Secret
          name: oauth2-proxy-secret
          valuesKey: ZITADEL_CLIENT_SECRET
        - targetPath: extraArgs.oidc-issuer-url
          kind: Secret
          name: oauth2-proxy-secret
          valuesKey: ZITADEL_ISSUER_URL
        - targetPath: config.cookieSecret
          kind: Secret
          name: oauth2-proxy-secret
          valuesKey: OAUTH2_PROXY_COOKIE_SECRET
