apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: firefly-importer
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: firefly-importer-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: firefly-importer
