apiVersion: v1
kind: Secret
metadata:
    name: firefly-import-secret
type: Opaque
stringData:
    accessToken: ENC[AES256_GCM,data:yYm4kH7f2bcFtKahcff0h3HZcG2wSQOwpPvkGDVV8kc=,iv:OpyC/AZA/sGmRoR1eGDJU+2YZpxace1aT3CIFfUWT7w=,tag:Rl+KERAKYC9P1flw3Y9fAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uklvgjw0zfn5qy8qcaggl0g9x3dk8ysq9f3my500vm567rkd2syqkxqgtw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNlQ0dC8yOGhsOXlJNVNS
            bUNmeDZ3S1QrWWI5MXJyc1NQTDA3cStteEVzCk9zLzZldlp3NEJydmVVYi85Uklw
            a0VXTnVIaVFUMEpxbWd0UVNRK1pkcXcKLS0tICtBSTk4Y3ZUc1daQXFrZGo3WTZs
            TGF3ZVVzeGg4dWQwRTNFczRpNjdlREkKU3nS0KyejTyK/NnlEjGD8aDfeVQXNGLb
            Wmx09cl2Zr+f1k4JxefyIVxUhRFO/P9ftAl9CrFUYgNw5a4zKycbqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-14T18:39:16Z"
    mac: ENC[AES256_GCM,data:UDlS4j7X2YkJDG16gjVLu+zZRuLPMje2HUvlHW7ie1ZzTvfYt/HiQ+NVNDmxSWQiqLmamxSocCzq1NwsUPyU+KE7EiAQslVxr6axeDloUOaHA+wZaQnDZErBd6DTHnUXvY9VPBSnrrpMcaezJqDryf+sRbiZ2wcLZ49m90Ncdfo=,iv:OgItcf8pMwLC+TVh4J6fgO5N4XpJUkD9YBlh7pRFdA0=,tag:bm6Sy7JE2VxK9Syp5IP+1w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
