namespace: firefly

resources:
  - ./namespace.yaml
  - ./externalsecret.yaml
  - ./externalsecret-importer.yaml

#generators:
#  - ./secret-generator.yaml

helmCharts:
  - name: firefly-iii
    repo: https://firefly-iii.github.io/kubernetes/
    releaseName: firefly-iii
    version: 1.7.1
    namespace: firefly
    valuesInline:
      service:
        port: 8080
      config:
        env:
          TZ: "Europe/Copenhagen"
          APP_ENV: production
          APP_DEBUG: 'true'
          APP_LOG_LEVEL: debug
          DB_HOST: cluster-01-haproxy.percona-xtradb
          DB_CONNECTION: mysql
          DB_PORT: 3306
          DB_DATABASE: firefly
          DB_USERNAME: firefly
          MAIL_MAILER: log
          MAIL_FROM: changeme@example.com
          AUTHENTICATION_GUARD: 'remote_user_guard'
          AUTHENTICATION_GUARD_HEADER: 'X-Email'
          TRUSTED_PROXIES: '**'
        existingSecret: firefly-secret
      cronjob:
        enabled: true
        auth:
          existingSecret: firefly-secret
          secretKey: "STATIC_CRON_TOKEN"
      ingress:
        enabled: true
        className: nginx
        annotations:
          nginx.ingress.kubernetes.io/auth-url: "https://auth.mlad.dk/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: "https://auth.mlad.dk/oauth2/start?rd=$escaped_request_uri"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            auth_request_set $user   $upstream_http_x_auth_request_user;
            auth_request_set $email  $upstream_http_x_auth_request_email;
            proxy_set_header X-User  $user;
            proxy_set_header X-Email $email;
        hosts:
          - budget.mlad.dk

  - name: app-template
    repo: https://bjw-s.github.io/helm-charts/
    releaseName: firefly-iii-importer-matthias
    version: 2.5.0
    namespace: firefly
    valuesInline:
      controllers:
        main:
          annotations:
            reloader.stakater.com/auto: "true"

#          pod:
#            securityContext:
#              runAsUser: 1000
#              runAsGroup: 1000
#              fsGroup: 1000
#              fsGroupChangePolicy: OnRootMismatch

          containers:
            main:
              #              securityContext:
              #                runAsUser: 0
              image:
                repository: fireflyiii/data-importer
                tag: "version-1.4.2"
              env:
                IGNORE_DUPLICATE_ERRORS: "false"
                TZ: "Europe/Copenhagen"
                FIREFLY_III_ACCESS_TOKEN:
                  valueFrom:
                    secretKeyRef:
                      name: firefly-importer-secret
                      key: matthias_access_token
                FIREFLY_III_URL: "http://firefly-iii.firefly.svc.local.homelab.mlad.dk:8080"
                VANITY_URL: "https://budget.mlad.dk"
                TRUSTED_PROXIES: "**"
              resources:
                requests:
                  cpu: 8m
                  memory: 50M
                limits:
                  memory: 256M

      service:
        main:
          ports:
            http:
              port: 8080

      ingress:
        main:
          enabled: true
          className: "nginx"
          annotations:
            nginx.ingress.kubernetes.io/auth-url: "https://auth.mlad.dk/oauth2/auth"
            nginx.ingress.kubernetes.io/auth-signin: https://auth.mlad.dk/oauth2/start
          hosts:
            - host: budget-matthias.mlad.dk
              paths:
                - path: /
                  service:
                    name: main
                    port: http

