namespace: firefly

resources:
  - ./namespace.yaml
  - ./externalsecret.yaml

#generators:
#  - ./secret-generator.yaml

helmCharts:
  - name: firefly-iii
    repo: https://firefly-iii.github.io/kubernetes/
    releaseName: firefly-iii
    version: 1.7.1
    namespace: firefly
    valuesInline:
      service:
        port: 8080
      config:
        env:
          TZ: "Europe/Copenhagen"
          APP_ENV: production
          APP_DEBUG: 'true'
          APP_LOG_LEVEL: debug
          DB_HOST: cluster-01-haproxy.percona-xtradb
          DB_CONNECTION: mysql
          DB_PORT: 3306
          DB_DATABASE: firefly
          DB_USERNAME: firefly
          MAIL_MAILER: log
          MAIL_FROM: changeme@example.com
        #          TRUSTED_PROXIES: '**'
        existingSecret: firefly-secret
      cronjob:
        enabled: true
        auth:
          existingSecret: firefly-secret
          secretKey: "STATIC_CRON_TOKEN"
      ingress:
        enabled: true
        className: nginx
        hosts:
          - budget.mlad.dk

  - name: importer
    repo: https://firefly-iii.github.io/kubernetes/
    releaseName: firefly-iii-importer-matthias
    version: 1.3.1
    namespace: firefly
    valuesInline:
      service:
        port: 8080
      config:
        env:
          IGNORE_DUPLICATE_ERRORS: "false"
          TZ: "Europe/Copenhagen"
          FIREFLY_III_CLIENT_ID: 10
        files: {}
      fireflyiii:
        url: "http://firefly-iii:8080"
        vanityUrl: "https://budget.mlad.dk"
#        auth:
#          existingSecret: firefly-import-secret
      ingress:
        enabled: true
        className: nginx
        hosts:
          - matthias.budget.mlad.dk

