namespace: firefly

resources:
  - ./namespace.yaml

generators:
  - ./secret-generator.yaml

helmCharts:
  - name: firefly-iii
    repo: https://firefly-iii.github.io/kubernetes/
    releaseName: firefly-iii
    version: 1.7.1
    namespace: firefly
    valuesInline:
      service:
        port: 8080
      config:
        env:
          APP_ENV: production
          DB_HOST: cluster-01-haproxy.percona-xtradb
          DB_CONNECTION: mysql
          DB_PORT: 3306
          DB_DATABASE: firefly
          DB_USERNAME: firefly
          MAIL_MAILER: log
          MAIL_FROM: changeme@example.com
#          TRUSTED_PROXIES: '**'
        existingSecret: firefly-env-secret
      cronjob:
        enabled: true
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - budget.mlad.dk

