apiVersion: v1
kind: Secret
metadata:
    name: mysecret
type: Opaque
data:
    username: ENC[AES256_GCM,data:axy9Kg==,iv:mT4Jmn75HEuq+8Fd0Ee55CSvp9hRHsNu1Pgic/TDWnM=,tag:xzpLp7cWnNBFHJgYy0vR9w==,type:str]
    password: ENC[AES256_GCM,data:Ww4YivpQB2VedHI=,iv:kAvOLHs7MTqDEgE8bZQ16pZQOWYsFUayJ51Egf0Q4jk=,tag:QPXPEWoLokaEMEaz/msRMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uklvgjw0zfn5qy8qcaggl0g9x3dk8ysq9f3my500vm567rkd2syqkxqgtw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2WXVFZDJSeHRVTlB4ZFEz
            TGltdWNWNThjb3NHZEI2djhuS3R5M3A5ZlFNCmdUaUduZHpvRGc4ZkNyTmlYbVBq
            TE5IMVZWRWJjNE1oZzBZbVk4QTY2aFEKLS0tIFVnRVRmK25ucU85bXRCUE9GSmlH
            TGoxckJFZ3MvQy9nUFRjUEJHOEtSY0EK5dWoxZk5Qbv1TWYXGdn4miAOmu4LOeky
            Q/sDTrOJFyFwzkZgwEhMTz43w28KOXQBYcOOaXcmNRySYk7ae/sZEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-13T10:10:22Z"
    mac: ENC[AES256_GCM,data:DUULD+dQjjNF9qJrr42B8eC5LvhBm7TZCnTSZklxJ1R/plQfQx/JF365+bG58sHksEmpZeShFsmSj7sMJTWgducxKeWa+4iGk0ZBEfYsYwiccMBP67xvGeIuA6R/I4lkrXy8uLSI5oSN068STWHI/seAG84+DM4txI0vZbvCG/M=,iv:i6GMC3GhBUsZCL4OlJJFqP9HzLfhDm3V98JYfKuYAMI=,tag:hgkfj4ZEt6ASCVrOLBLdFw==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.8.1
