apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  # Specify a name
  name: firefly-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./secret.sops.yaml
  - ./cron-secret.sops.yaml
  - ./import-secret.sops.yaml
