apiVersion: v1
kind: Secret
metadata:
    name: firefly-env-secret
type: Opaque
stringData:
    APP_PASSWORD: ENC[AES256_GCM,data:RNi5OvxjIYc=,iv:BkEw9oxwzdldsnNVt2TuT0jmjRY/+P9SEYt/1cIhass=,tag:cmWQG9QT63qPAh5Zhhk7eA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:FbTh7SSBb2vaXGMZ3NtDckckGw==,iv:YFiAya02zyvaZwL2j4L8OM4qMKApAvd1AjSwoInY5E0=,tag:AIjD37Y1IdiOKvvGOPSLcQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uklvgjw0zfn5qy8qcaggl0g9x3dk8ysq9f3my500vm567rkd2syqkxqgtw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcDFPR2h6ajcwaWdkdGx1
            V0NDbnhPQVd0bFRLYkxiYjBZWG02MnAydmowCmdZNmNURTV1NmVsOWJ6YWxWL1NB
            SnNhcnlodkVkSjNqWFdBMzZIbmtOSTgKLS0tIExtUVB1ZnVRQjJyaWlrcTRrR2pV
            Zk5TMDRMNFVSQUk4bUNwTTZnSFV2QjAKSvH+0DGq+s0SAZoCzMEKEHmRu7u9s6fx
            x2H48RBxpaBubemmCgvV4oejM6tID7TcQrfbyFE4jfB9JO7iMIWcUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-14T15:56:49Z"
    mac: ENC[AES256_GCM,data:KP2JAHVACurYGgLVmEv/ntkYQDHjQw9aFZ8My2wbDyX2o6lHIMy7w0IH+2/7GRFoQcaUjt7TtyeTdKNpLvRZWp0Kcv636XJ2K1IfvhKVaAULg43AS8VpeUrZC4+x9c/uVt0w71ITtTMz3GCCRN10Yp5x/vvfTgmFcQdfgbj4xxQ=,iv:IzrcAxDL2X7MhTzvVJU1lZFbVt4f2BuzCtxzJ8CLJg8=,tag:DPr5dU/T1ic5qc/jGCoNLA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
