resources:
  - ./namespace.yaml

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    version: 0.9.11
    namespace: kube-system
    valuesInline:
      installCRDs: true
      replicaCount: 1
      serviceMonitor:
        enabled: true
      webhook:
        serviceMonitor:
          enabled: true
      certController:
        serviceMonitor:
          enabled: true
