apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zigbee2mqtt
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: zigbee2mqtt-secret
    creationPolicy: Owner
  data:
    - secretKey: mqtt_user
      remoteRef:
        key: emqx
        property: EMQX_AUTH__USER__1__USERNAME
    - secretKey: mqtt_password
      remoteRef:
        key: emqx
        property: EMQX_AUTH__USER__1__PASSWORD
    - secretKey: zigbee_pan_id
      remoteRef:
        key: zigbee2mqtt
        property: config_pan_id
    - secretKey: zigbee_ext_pan_id
      remoteRef:
        key: zigbee2mqtt
        property: config_ext_pan_id
