namespace: home-automation

resources:
  - ./externalsecret.yaml

#generators:
#  - ./secret-generator.yaml

helmCharts:
  - name: app-template
    repo: https://bjw-s.github.io/helm-charts/
    releaseName: zigbee2mqtt
    version: 2.5.0
    namespace: home-automation
    valuesInline:
      controllers:
        main:
          annotations:
            reloader.stakater.com/auto: "true"

          pod:
            securityContext:
              privileged: true
              runAsUser: 1000
              runAsGroup: 1000
              fsGroup: 1000
              fsGroupChangePolicy: OnRootMismatch

          containers:
            main:
              securityContext:
                runAsUser: 0
              image:
                repository: ghcr.io/koenkk/zigbee2mqtt
                tag: 1.35.1
              env:
                ZIGBEE2MQTT_DATA: /data
                ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_DISCOVERY_TOPIC: homeassistant
                ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_LEGACY_ENTITY_ATTRIBUTES: "false"
                ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_LEGACY_TRIGGERS: "false"
                ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_STATUS_TOPIC: homeassistant/status
                ZIGBEE2MQTT_CONFIG_ADVANCED_LAST_SEEN: ISO_8601
                ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_API: "false"
                ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_AVAILABILITY_PAYLOAD: "false"
                ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_LEVEL: debug
                ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_OUTPUT: '["console"]'
                ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID:
                  valueFrom:
                    secretKeyRef:
                      name: zigbee2mqtt-secret
                      key: zigbee_ext_pan_id
                ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID:
                  valueFrom:
                    secretKeyRef:
                      name: zigbee2mqtt-secret
                      key: zigbee_pan_id
                ZIGBEE2MQTT_CONFIG_AVAILABILITY_ACTIVE_TIMEOUT: 60
                ZIGBEE2MQTT_CONFIG_AVAILABILITY_PASSIVE_TIMEOUT: 2000
                ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_LEGACY: "false"
                ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_RETAIN: "true"
                ZIGBEE2MQTT_CONFIG_EXPERIMENTAL_NEW_API: "true"
                ZIGBEE2MQTT_CONFIG_FRONTEND: "false"
#                ZIGBEE2MQTT_CONFIG_FRONTEND_PORT: "8080"
                ZIGBEE2MQTT_CONFIG_FRONTEND_URL: https://zigbee2mqtt.mlad.dk
                ZIGBEE2MQTT_CONFIG_HOMEASSISTANT: "true"
                ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC: zigbee2mqtt
                ZIGBEE2MQTT_CONFIG_MQTT_INCLUDE_DEVICE_INFORMATION: "true"
                ZIGBEE2MQTT_CONFIG_MQTT_KEEPALIVE: 60
                ZIGBEE2MQTT_CONFIG_MQTT_REJECT_UNAUTHORIZED: "true"
                ZIGBEE2MQTT_CONFIG_MQTT_SERVER: "mqtt://emqx.default.svc.local.homelab.mlad.dk"
                ZIGBEE2MQTT_CONFIG_MQTT_VERSION: 5
                ZIGBEE2MQTT_CONFIG_MQTT_USER:
                  valueFrom:
                    secretKeyRef:
                      name: zigbee2mqtt-secret
                      key: mqtt_user
                ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD:
                  valueFrom:
                    secretKeyRef:
                      name: zigbee2mqtt-secret
                      key: mqtt_password
#                ZIGBEE2MQTT_CONFIG_PERMIT_JOIN: "false"
                ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER: ezsp
                ZIGBEE2MQTT_CONFIG_SERIAL_PORT: "/dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20231008143900-if00"
#                ZIGBEE2MQTT_CONFIG_SERIAL_BAUDRATE: 460800
#                ZIGBEE2MQTT_CONFIG_SERIAL_DISABLE_LED: false
              resources:
                requests:
                  cpu: 8m
                  memory: 212M
                limits:
                  memory: 256M

          initContainers:
            usb-permission:
              name: usb-perm
              image:
                repository: busybox
                tag: latest
              securityContext:
                runAsUser: 0
              command: [ "sh","-c","ls -al /dev/serial/by-id && chmod 777 /dev/serial/by-id/usb* && ls -al /dev/serial/by-id && chown 1000:1000 /dev/serial/by-id/usb* && test -w /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20231008143900-if00 && echo success || echo failure" ]
              resources:
                limits:
                  cpu: 5m
                  memory: 10Mi

          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: sonoff.tech/zigbee-dongle-plus-e
                        operator: In
                        values:
                          - "true"

      service:
        main:
          ports:
            http:
              port: 8080
            metrics:
              enabled: true
              port: 9000

      ingress:
        main:
          enabled: true
          className: "nginx"
          annotations:
            nginx.ingress.kubernetes.io/auth-url: "https://auth.mlad.dk/oauth2/auth"
            nginx.ingress.kubernetes.io/auth-signin: https://auth.mlad.dk/oauth2/start
          hosts:
            - host: zigbee2mqtt.mlad.dk
              paths:
                - path: /
                  service:
                    name: main
                    port: http

      persistence:
        data:
          accessMode: ReadWriteOnce
          size: "1Gi"
          advancedMounts:
            main:
              main:
                - path: /data
        usb:
          enabled: true
          type: hostPath
#          hostPath: /dev/serial/by-id/usb-1a86_55d4-if00
          hostPath: /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20231008143900-if00
#          hostPath: /dev/ttyACM0
          hostPathType: CharDevice
#          defaultMode: 511 # 0700
