apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: node-red-ssh
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: node-red-ssh
    creationPolicy: Owner
  data:
    - secretKey: private
      remoteRef:
        key: node-red
        property: ssh-key-private
    - secretKey: public
      remoteRef:
        key: node-red
        property: ssh-key-public
