namespace: node-red

resources:
  - ./namespace.yaml

#generators:
#  - ./secret-generator.yaml

helmCharts:
  - name: app-template
    repo: https://bjw-s.github.io/helm-charts/
    releaseName: node-red
    version: 1.5.1
    namespace: node-red
    valuesInline:
      image:
        repository: nodered/node-red
        tag: 3.1.3-18-minimal

      env:
        TZ: "Europe/Copenhagen"
        FLOWS: "flows.json"
        NODE_RED_ENABLE_PROJECTS: "true"
        NODE_RED_ENABLE_SAFE_MODE: "false"

      service:
        main:
          ports:
            http:
              port: 1880

      ingress:
        main:
          enabled: true
          ingressClassName: "nginx"
          annotations:
            nginx.ingress.kubernetes.io/auth-url: "https://auth.mlad.dk/oauth2/auth"
            nginx.ingress.kubernetes.io/auth-signin: https://auth.mlad.dk/oauth2/start
          hosts:
            - host: node-red.mlad.dk
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - node-red.mlad.dk

      podSecurityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"

      persistence:
        data:
          enabled: true
          mountPath: /data
#          storageClass: "rook-ceph-block"
          accessMode: ReadWriteOnce
          size: "5Gi"

      tolerations:
        - key: "arm"
          operator: "Exists"

      resources:
        requests:
          memory: 350Mi
          cpu: 25m
        limits:
          memory: 500Mi

#configMapGenerator:
#  - name: node-red-configmap
#    files:
#      - config/settings.js
#generatorOptions:
#  disableNameSuffixHash: true
#  annotations:
#    kustomize.toolkit.fluxcd.io/substitute: disabled
