namespace: home-automation

resources:
  - ./externalsecret.yaml

#generators:
#  - ./secret-generator.yaml

helmCharts:
  - name: app-template
    repo: https://bjw-s.github.io/helm-charts/
    releaseName: home-assistant
    version: 2.5.0
    namespace: home-automation
    valuesInline:
      defaultPodOptions:
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
          fsGroupChangePolicy: OnRootMismatch

      controllers:
        main:
          annotations:
            reloader.stakater.com/auto: "true"

#            annotations:
#              k8s.v1.cni.cncf.io/networks: |
#                [{
#                  "name":"multus-iot",
#                  "namespace": "network",
#                  "ips": ["192.168.100.50/24"]
#                }]

          containers:
            main:
              image:
                repository: ghcr.io/home-assistant/home-assistant
                tag: 2024.1.6
              envFrom:
                - secretRef:
                    name: home-assistant-secret
              probes:
                liveness:
                  enabled: false
                readiness:
                  enabled: false
                startup:
                  enabled: false
              resources:
                requests:
                  cpu: 47m
                  memory: 1254M
                limits:
                  memory: 1254M

            vscode:
              image:
                repository: codercom/code-server
                tag: 4.21.0
              workingDir: "/config"
              args:
                - --user-data-dir
                - "/config/.vscode"
                - --auth
                - "none"
              env:
                TZ: America/New_York
                HASS_SERVER: http://home-assistant:8123
              probes:
                liveness:
                  enabled: false
                readiness:
                  enabled: false
                startup:
                  enabled: false

          initContainers:
            git-clone:
              name: git-clone
              image:
                repository: alpine/git
                tag: latest
              command:
                - sh
                - -c
                - git clone --single-branch https://github.com/connors511/hass-config.git /config || true


      service:
        main:
          ports:
            http:
              port: 8123
            vscode:
              port: 8080

      ingress:
        main:
          enabled: true
          className: "nginx"
          annotations:
            nginx.ingress.kubernetes.io/auth-url: "https://auth.mlad.dk/oauth2/auth"
            nginx.ingress.kubernetes.io/auth-signin: https://auth.mlad.dk/oauth2/start
          hosts:
            - host: hass.mlad.dk
              paths:
                - path: /
                  service:
                    name: main
                    port: http
            - host: hass-code.mlad.dk
              paths:
                - path: /
                  service:
                    name: main
                    port: vscode

      persistence:
        data:
          accessMode: ReadWriteOnce
          size: "1Gi"
          globalMounts:
            - path: /config
        deploy-key:
          type: secret
          name: home-assistant-secret
          defaultMode: 256
          globalMounts:
            - path: /root/.ssh/id_rsa
              subPath: GH_DEPLOY_KEY
