apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-feature-discovery
  namespace: argocd
spec:
  project: platform
  source:
    helm:
      version: v3
    path: platform/node-feature-discovery
    repoURL: https://github.com/connors511/homelab-gitops.git
    targetRevision: HEAD
  destination:
    namespace: node-feature-discovery
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
