namespace: network

resources:
  - ./namespace.yaml
  - ./net-attach-iot.yaml

helmCharts:
  - name: multus
    releaseName: multus
    repo: https://angelnu.github.io/helm-charts
    version: 5.0.4
    namespace: network
    includeCRDs: true
    valuesInline:
      image:
        repository: ghcr.io/k8snetworkplumbingwg/multus-cni
        tag: v4.0.2-thick

      cni:
        image:
          repository: ghcr.io/angelnu/cni-plugins
          tag: 1.4.0

        paths:
          config: /etc/cni/net.d
          bin: /opt/cni/bin

      resources:
        requests:
          cpu: 5m
          memory: 96Mi
        limits:
          memory: 96Mi

      hostPaths:
        netns: /var/run/netns
