helmCharts:
  - name: whoami
    repo: https://cowboysysop.github.io/charts/
    releaseName: whoami
    version: 5.1.0
    valuesInline:
      replicaCount: 2
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/auth-url: "https://auth.mlad.dk/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: "https://auth.mlad.dk/oauth2/start"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            auth_request_set $token $upstream_http_authorization;
            proxy_set_header Authorization $token;
            
            auth_request_set $user   $upstream_http_x_auth_request_user;
            auth_request_set $email  $upstream_http_x_auth_request_email;
            proxy_set_header X-User  $user;
            proxy_set_header X-Email $email;
        pathType: Prefix
        hosts:
          - host: whoami.mlad.dk
            paths:
              - "/"
