helmCharts:
  - name: whoami
    repo: https://cowboysysop.github.io/charts/
    releaseName: whoami
    version: 5.1.0
    valuesInline:
      replicaCount: 2
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
        pathType: Prefix
        hosts:
          - host: whoami.mlad.dk
            paths:
              - "/"
