apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami
  namespace: argocd
spec:
  project: applications
  source:
    chart: cowboysysop/whoami
    repoURL: https://cowboysysop.github.io/charts/
#    repoURL: https://github.com/cowboysysop/charts/tree/master/charts/whoami
    targetRevision: 'latest'
    helm:
      valuesObject:
        replicaCount: 2
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "nginx"
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          hosts:
            - host: whoami.mlad.dk
              paths:
                - "/"
          pathType: Prefix
  destination:
    server: https://kubernetes.default.svc
    namespace: whoami
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 2
      backoff:
        duration: "5s"
        factor: 2
        maxDuration: "3m0s"
